### PR TITLE
vnext (for comparison)

### PR DESCRIPTION
**Pull request by kraigb**
This PR is only to show the diff; not intended for merging at this time.

### CODE REVIEW

**Comment by sptramer** [comment]
@kraigb Let me kn.ow when you're ready for a formal review on this.

**Comment by kraigb** [comment]
Review can happen any time...I'm done with this round of work.

**Comment by sptramer** [comment]
@kraigb Can you resolve the conflicts? Then I'll start review+merge.

**Comment by kraigb** [comment]
Well, I was trying to resolve the conflicts but the damn process decided to merge it all. You can still take a look through the changed files, though.

**Pull request merged**
